# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
title: Entertainment Education
description: >- # this means to ignore newlines until "baseurl:"
  Grade 12-Krypton Students from PSHS-CLC who want to talk about entertainment.
baseurl: "/portfolio"
url: "https://hasonon.github.io"
#twitter_username: username
#github_username: hasonon
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _posts
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Entertainment Education"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Grade 12-Krypton Students from PSHS-CLC who want to talk about entertainment."
  links:
    - label: "PSHS-CLC"
      icon: "fas fa-school"
      url: "https://clc.pshs.edu.ph/"
    - label: "K-Hub"
      icon: "fas fa-globe"
      url: "https://khub.clc.pshs.edu.ph/"
footer:
  links:
    - label: "PSHS-CLC"
      icon: "fas fa-school"
      url: "https://clc.pshs.edu.ph/"
    - label: "K-Hub"
      icon: "fas fa-globe"
      url: "https://khub.clc.pshs.edu.ph/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

